bmpn:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features: []
  l10n: ru
  modules:
  - core:
      entities: []
  application: 
  - workflows
  scripts:
  - camunda_db
  - camunda/postgres_engine_7.12.0
  - camunda/postgres_identity_7.12.0
  - users
  includes:
  - common
