bmpn:
  projectFileStructure: {}
  features: []
  l10n: ru
  modules:
  - core:
      entities: []
  application: 
  - _workflows_
  scripts:
  - camunda_db
  - camunda/postgres_engine_7.12.0
  - camunda/postgres_identity_7.12.0
  includes:
  - common
